Fix

diff --git a/.github/workflows/create-feedstock.yaml b/.github/workflows/create-feedstock.yaml
--- a/.github/workflows/create-feedstock.yaml
+++ b/.github/workflows/create-feedstock.yaml
@@ -3,22 +3,27 @@ on:
     branches: [master]
 
 jobs:
-  - name: Get changed files
-    id: changed-files
-    # Set outputs using the command.
-    run: |
-      echo "::set-output name=all::$(git diff --name-only origin/master HEAD | xargs)"
-  - name: Locate pr meta.yaml
-    id: meta
-    run: |
-      for changed_file in ${{ steps.changed-files.outputs.all }}; do
-      if [[ ${changed_file} =~ ^.*recipes\/.*meta\.(yml|yaml)$ ]];
-      then
-        echo "::set-output name=META_YAML::${changed_file}";
-        exit 0
-      fi
-    done
-    exit 1 # Fail - meta.yaml required
- - name: Print meta
-   run: |
-     echo  "${{ steps.meta.outputs.META_YAML }}"
+  create-feedstock:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Get changed files
+        id: changed-files
+        # Set outputs using the command.
+        run: |
+          echo "::set-output name=all::$(git diff --name-only origin/master HEAD | xargs)"
+
+      - name: Locate pr meta.yaml
+        id: meta
+        run: |
+          for changed_file in ${{ steps.changed-files.outputs.all }}; do
+            if [[ ${changed_file} =~ ^.*recipes\/.*meta\.(yml|yaml)$ ]];
+            then
+              echo "::set-output name=META_YAML::${changed_file}";
+              exit 0
+            fi
+          done
+          exit 1 # Fail - meta.yaml required
+
+      - name: Print meta
+        run: |
+          echo  "${{ steps.meta.outputs.META_YAML }}"
